# Generated by Django 3.2.3 on 2021-05-26 22:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='djangoclasses',
            managers=[
                ('objectscd', django.db.models.manager.Manager()),
            ],
        ),
    ]
