# Generated by Django 3.2.3 on 2021-05-26 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0002_alter_djangoclasses_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='djangoclasses',
            managers=[
            ],
        ),
    ]
